markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]

name: Борислав Ларін
url: http://brabadu.com
description: Про життя
twitter: brabadu
github: brabadu
gravatar_url: http://gravatar.com/avatar/f97f29382b72cc9fefc973750fde6125